services:
  node:
    build: ./node
    image: consistent-hashing_node:latest
    environment:
      - NODE_ID=node1
    networks:
      - ringnet
    deploy:
      replicas: 2
    labels:
      - service=node

  loadbalancer:
    build: ./loadbalancer
    ports:
    - "8080:8080"
    environment:
      - NODE_IMAGE=consistent-hashing_node:latest
    networks:
      - ringnet
    depends_on:
      - node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dashboard:
    build: ./dashboard
    ports:
      - "8000:80"
    networks:
      - ringnet

networks:
  ringnet:
    driver: bridge